### ISSUE TITLE
Ignoring Radiotap Headers/80211 frames

### ISSUE THREAD

**Issue by stephengroat** [isginf/pcap-diff#7]
since Radiotap headers have time stamps and other dynamic information in them (channel freq., etc), it would be nice to be able to ignore them with ignore all layer below (i.e. the rest of the packet)

**Comment by balle** [comment]
Hi,

I introduced new parameter -L to specify the first layer of interest. Everything below is ignored.
Hope this solves your issue.

Have a nice day!

Basti

**Comment by stephengroat** [comment]
thanks!
